env_paths:
  python_venv_dir: .venv
  scripts_dir: py/src
  download_dir: /appdata/download
  import_dir: /appdata/import
  training_dir: /appdata/training
  model_dir: /appdata/models
db_config:
  url: postgres://postgres:bear@db-tastehead:5432/tasteheaddb?sslmode=disable
logger:
  timestamp: "2006-01-02 15:04:05"
  formatlevel: "%-6s"
  level: debug
server:
  port: 8080
